# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('about', markdownx.models.MarkdownxField()),
                ('location', models.TextField(blank=True)),
                ('meedup_link', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
